export const CITATIONS_DATA = {
  1: {
    id: 1,
    status: 'PRIMARY VERIFIED',
    title: 'Mumbai Protests Enter Third Week',
    scannedIngestion: '2024-03-11 · Node: Asia-South-1',
    author: 'Rahul Mehta',
    publication: 'The Daily Chronicle (Print Edition)',
    date: 'June 18, 2019',
    location: 'Page 3, Column 2 (Morning National)',
    archiveRef: 'ARCH-2019-MUM-0842',
    integrity: 'Cold Vault B · MD5: e29a3f...b891 [Verified]',
    permastring: 'perm://archive.mediamind.internal/vault-b/2019/mum/0842#sec-b-p3',
    sectionHeader: 'Developments — Page 3, Section B',
    scanResolution: 'Scan Resolution: 600 DPI',
    zoom: 'Zoom 100%',
    ocrStreamMeta: 'ARCHIVAL OCR STREAM Page 3, Col 2, Lines 14-38',
    encoding: 'ENCODING: UTF-8 / RAW_FACSIMILE',
    preMatchText: 'Municipal representatives reiterated on Monday morning that construction timelines for the coastal freeway connector remained unchanged despite mounting public scrutiny. However, in the districts surrounding Azad Maidan and Churchgate station, civilian assemblies showed no signs of abating.',
    exactPassage: '“The demonstrations continued into their third week, with organizers estimating that several thousand participants gathered across multiple locations in South Mumbai, demanding an immediate stay on reclamation activities until environmental review boards complete their audit.”',
    relevance: '99.2% RELEVANCE',
    postMatchText: 'Police spokespersons reported that traffic diversions had been enacted across three arterial junctions by midday, though no arrests had been recorded as of press time.',
    confidence: '99.2% (Exact Lexical & Semantic Match)',
    justificationHtml: 'This passage directly validates the AI synthesis claim regarding the duration (<strong>"into their third week"</strong>) and scale (<strong>"several thousand participants gathered"</strong>) of the June 2019 demonstrations. No semantic drift or hallmarked extrapolation detected in corresponding synthetic sentence.',
    tags: [
      { label: 'Temporal Alignment', value: 'Validated', icon: 'check' },
      { label: 'Geographic Scope', value: 'South Mumbai', icon: 'map' },
      { label: 'Attribution Class', value: 'Primary Press', icon: 'building' }
    ],
    targetClaim: 'Archival evidence confirms that civil mobilization persisted unabated well into mid-June, with independent observers documenting widespread assemblies numbering in the thousands that disrupted commercial corridors across South Mumbai [1]'
  },
  2: {
    id: 2,
    status: 'PRIMARY VERIFIED',
    title: 'Brihanmumbai Municipal Press Release #114',
    scannedIngestion: '2024-03-09 · Node: Asia-South-1',
    author: 'Chief Engineer, Coastal Road Project',
    publication: 'Municipal Corporation of Greater Mumbai Bulletin',
    date: 'June 19, 2019',
    location: 'Official Gazette Record, Vol. 44',
    archiveRef: 'ARCH-2019-MUM-0901',
    integrity: 'Cold Vault A · MD5: d74b12...a904 [Verified]',
    permastring: 'perm://archive.mediamind.internal/vault-a/2019/mum/0901#bulletin-114',
    sectionHeader: 'Executive Briefings — Circular 114',
    scanResolution: 'Scan Resolution: 600 DPI',
    zoom: 'Zoom 100%',
    ocrStreamMeta: 'ARCHIVAL OCR STREAM Page 1, Official Seal Section',
    encoding: 'ENCODING: UTF-8 / RAW_FACSIMILE',
    preMatchText: 'The project execution division held a scheduled press briefing at the engineering annex. Senior supervisors reviewed reclamation milestones along the southern coastline sector.',
    exactPassage: '“Work on the Southern Coastal Corridor reclamation continues strictly in accordance with approved milestone dates, and civic authorities have sanctioned no modifications to ongoing civil engineering shifts notwithstanding ongoing representation by civic coalitions.”',
    relevance: '98.7% RELEVANCE',
    postMatchText: 'The communique reiterated that contractual penalties would apply should any contractor halt maritime dredging operations prior to the onset of the southwest monsoon.',
    confidence: '98.7% (High Direct Correlation)',
    justificationHtml: 'Corroborates that municipal administrative entities explicitly maintained active construction schedules and granted no public concessions during the demonstration cycle.',
    tags: [
      { label: 'Temporal Alignment', value: 'Synchronous', icon: 'check' },
      { label: 'Geographic Scope', value: 'Coastal Reclamation Sector A', icon: 'map' },
      { label: 'Attribution Class', value: 'Government Official', icon: 'building' }
    ],
    targetClaim: 'while civic municipal entities maintained their construction timelines without public concession [2]'
  },
  3: {
    id: 3,
    status: 'JUDICIAL ARCHIVE',
    title: 'Interim Writ Petition (PIL) No. 419 of 2019',
    scannedIngestion: '2024-02-28 · Node: Asia-South-2',
    author: 'Registrar, High Court of Judicature at Bombay',
    publication: 'Bombay High Court Records (Appellate Jurisdiction)',
    date: 'June 22, 2019',
    location: 'Courtroom 3, Bench Order Series 19-B',
    archiveRef: 'ARCH-2019-BHC-0419',
    integrity: 'Cold Vault C · MD5: 9c0e3a...4f12 [Verified]',
    permastring: 'perm://archive.mediamind.internal/vault-c/2019/bhc/0419#order-interim',
    sectionHeader: 'Bench Orders — Traffic Circulation Directives',
    scanResolution: 'Scan Resolution: 600 DPI',
    zoom: 'Zoom 100%',
    ocrStreamMeta: 'ARCHIVAL OCR STREAM Page 7, Paragraph 12-18',
    encoding: 'ENCODING: UTF-8 / RAW_FACSIMILE',
    preMatchText: 'Counsel representing the citizens collective submitted transit logs indicating emergency vehicle blockades along Mahapalika Marg and adjacent railway feeder routes.',
    exactPassage: '“The Traffic Advisory Department shall enforce staged perimeter diversions surrounding Churchgate terminus and Veer Nariman road between 08:00 and 19:00 hours to maintain ingress for essential public healthcare vehicles.”',
    relevance: '97.9% RELEVANCE',
    postMatchText: 'Hearing was posted for further affidavits to be filed by the maritime ecological oversight committee within two weeks.',
    confidence: '97.9% (Judicial Registry Match)',
    justificationHtml: 'Directly anchors the claim that arterial junctions surrounding Churchgate underwent judicial and municipal phased vehicular rerouting.',
    tags: [
      { label: 'Temporal Alignment', value: 'Validated', icon: 'check' },
      { label: 'Geographic Scope', value: 'Churchgate / Nariman Pt', icon: 'map' },
      { label: 'Attribution Class', value: 'Judicial Directive', icon: 'building' }
    ],
    targetClaim: 'Judicial interventions filed in the subsequent session noted that arterial junctions surrounding Churchgate experienced phased detours [3]'
  },
  4: {
    id: 4,
    status: 'OFFICIAL RECORD',
    title: 'Daily Police Commissionerate SitRep Log #170',
    scannedIngestion: '2024-03-01 · Node: Asia-South-1',
    author: 'Deputy Commissioner of Police (Zone 1)',
    publication: 'Mumbai Police Law & Order Intelligence Bulletin',
    date: 'June 23, 2019',
    location: 'South Region Headquarters, Special Branch',
    archiveRef: 'ARCH-2019-MUMPOL-0170',
    integrity: 'Cold Vault B · MD5: ff318c...002a [Verified]',
    permastring: 'perm://archive.mediamind.internal/vault-b/2019/mumpol/0170#sitrep',
    sectionHeader: 'Law Enforcement Situation Report — South Division',
    scanResolution: 'Scan Resolution: 600 DPI',
    zoom: 'Zoom 100%',
    ocrStreamMeta: 'ARCHIVAL OCR STREAM Summary Table Log 23-06',
    encoding: 'ENCODING: UTF-8 / RAW_FACSIMILE',
    preMatchText: 'Zone 1 patrol units deployed preventive monitoring cordons across Regal Circle, Metro Junction, and Marine Drive walkways from early morning.',
    exactPassage: '“Civil order was managed via proactive barricading and crowd channelization; zero formal preventive detentions or custodial bookings were registered across South Zone police stations for the twenty-four hour period ending 1800 hrs.”',
    relevance: '99.5% RELEVANCE',
    postMatchText: 'Field commanders reported full cooperation from rally organizers regarding clearance of arterial carriage-ways by sunset.',
    confidence: '99.5% (Exact Administrative Confirmation)',
    justificationHtml: 'Validates that law enforcement issued specific communiques stating no formal detentions or physical arrests occurred during this demonstration wave.',
    tags: [
      { label: 'Temporal Alignment', value: 'Validated', icon: 'check' },
      { label: 'Geographic Scope', value: 'Mumbai South Zone', icon: 'map' },
      { label: 'Attribution Class', value: 'Police Log', icon: 'building' }
    ],
    targetClaim: 'though law enforcement communiques emphasized that no formal physical detentions were initiated during this specific demonstration cycle [4]'
  },
  5: {
    id: 5,
    status: 'ARCHIVAL MEMO',
    title: 'Port Trust Marine Ingress Traffic Ledger',
    scannedIngestion: '2024-03-05 · Node: Asia-South-1',
    author: 'Harbour Master Office',
    publication: 'Mumbai Port Authority Operations Log',
    date: 'June 15, 2019',
    location: 'Dock Operations Annex III',
    archiveRef: 'ARCH-2019-MBPT-0082',
    integrity: 'Cold Vault A · MD5: 5a812f...c319 [Verified]',
    permastring: 'perm://archive.mediamind.internal/vault-a/2019/mbpt/0082',
    sectionHeader: 'Marine Navigation — Maritime Barges Log',
    scanResolution: 'Scan Resolution: 600 DPI',
    zoom: 'Zoom 100%',
    ocrStreamMeta: 'ARCHIVAL OCR STREAM Line Log 44-59',
    encoding: 'ENCODING: UTF-8 / RAW_FACSIMILE',
    preMatchText: 'Coastal barge dredging operations reported slight channel shifts due to artisanal fishing craft rallies near the harbor mouth.',
    exactPassage: '“Reclamation transport hopper barges maintained scheduled rotation between offshore borrow pits and Worli shoreline under tug escort without maritime safety halts.”',
    relevance: '96.4% RELEVANCE',
    postMatchText: 'Coast Guard safety warnings remained at Level 2 throughout the week.',
    confidence: '96.4% (Maritime Log Corroboration)',
    justificationHtml: 'Corroborates background port authority transit manifests used in calculating escalation and reclamation metrics.',
    tags: [
      { label: 'Temporal Alignment', value: 'Validated', icon: 'check' },
      { label: 'Geographic Scope', value: 'Mumbai Harbour & Shore', icon: 'map' },
      { label: 'Attribution Class', value: 'Port Authority', icon: 'building' }
    ],
    targetClaim: 'official port authority transit manifests [5]'
  },
  6: {
    id: 6,
    status: 'PRIMARY VERIFIED',
    title: 'Department of Environment & Forests Sanction Note',
    scannedIngestion: '2024-03-02 · Node: Asia-South-1',
    author: 'Principal Secretary (Environment)',
    publication: 'State Environmental Appraisal Committee Records',
    date: 'May 28, 2019',
    location: 'Mantralaya Administrative Records',
    archiveRef: 'ARCH-2019-MAH-ENV-011',
    integrity: 'Cold Vault B · MD5: 88fa39...11cd [Verified]',
    permastring: 'perm://archive.mediamind.internal/vault-b/2019/env/011',
    sectionHeader: 'Clearance Sanction Memorandum',
    scanResolution: 'Scan Resolution: 600 DPI',
    zoom: 'Zoom 100%',
    ocrStreamMeta: 'ARCHIVAL OCR STREAM Page 2, Cl. 4-9',
    encoding: 'ENCODING: UTF-8 / RAW_FACSIMILE',
    preMatchText: 'Following statutory review of reclamation baseline bathymetry and benthic fauna surveys, committee convened for final ratification.',
    exactPassage: '“Conditional environmental clearance is accorded for Section 1 reclamation works subject to continuous quarterly benthic ecosystem audits and littoral drift mitigation.”',
    relevance: '98.1% RELEVANCE',
    postMatchText: 'Citizen grievance petitions submitted prior to May 25 were taken on record as Annexure B.',
    confidence: '98.1% (Regulatory Sanction Match)',
    justificationHtml: 'Anchors the statement that initial unrest surfaced in late May following the municipal corporation’s environmental clearance ratification.',
    tags: [
      { label: 'Temporal Alignment', value: 'Late May 2019', icon: 'check' },
      { label: 'Geographic Scope', value: 'State Secretariat', icon: 'map' },
      { label: 'Attribution Class', value: 'Statutory Body', icon: 'building' }
    ],
    targetClaim: 'following the municipal corporation\'s environmental clearance ratification [6]'
  },
  7: {
    id: 7,
    status: 'PRESS ARCHIVE',
    title: 'Western Railway Commuter Disruption Bulletin',
    scannedIngestion: '2024-03-12 · Node: Asia-South-1',
    author: 'Public Relations Officer, Western Railway',
    publication: 'Railway Administration Press Desk',
    date: 'June 17, 2019',
    location: 'Headquarters, Churchgate',
    archiveRef: 'ARCH-2019-WR-0914',
    integrity: 'Cold Vault A · MD5: bb716a...9902 [Verified]',
    permastring: 'perm://archive.mediamind.internal/vault-a/2019/wr/0914',
    sectionHeader: 'Transit Operations — Commuter Advisory',
    scanResolution: 'Scan Resolution: 600 DPI',
    zoom: 'Zoom 100%',
    ocrStreamMeta: 'ARCHIVAL OCR STREAM Advisory Notice 44',
    encoding: 'ENCODING: UTF-8 / RAW_FACSIMILE',
    preMatchText: 'Suburban train services operated on normal timetable despite heavy commuter bottlenecks outside south concourse exits.',
    exactPassage: '“Suburban train services on Western Railway operated to schedule, with station entry gates at Churchgate East regulated intermittently due to citizen gathering outside the municipal building.”',
    relevance: '97.2% RELEVANCE',
    postMatchText: 'Additional RPF and GRP personnel were posted on footbridges as a precautionary measure.',
    confidence: '97.2% (Transit Logistics Verification)',
    justificationHtml: 'Validates that assemblies concentrated adjacent to transport hubs and administrative headquarters during mid-June.',
    tags: [
      { label: 'Temporal Alignment', value: 'Mid-June 2019', icon: 'check' },
      { label: 'Geographic Scope', value: 'Churchgate Terminal', icon: 'map' },
      { label: 'Attribution Class', value: 'Transit Agency', icon: 'building' }
    ],
    targetClaim: 'concentrated adjacent to transport hubs and administrative headquarters [7]'
  },
  8: {
    id: 8,
    status: 'PRIMARY VERIFIED',
    title: 'Fisherfolk Cooperative Collective Joint Memorandum',
    scannedIngestion: '2024-03-08 · Node: Asia-South-1',
    author: 'Akhil Maharashtra Macchimar Kriti Samiti',
    publication: 'Archived Representation Dossier #19',
    date: 'June 14, 2019',
    location: 'Worli Koliwada Community Hall',
    archiveRef: 'ARCH-2019-AMMKS-0019',
    integrity: 'Cold Vault C · MD5: 33ee41...9821 [Verified]',
    permastring: 'perm://archive.mediamind.internal/vault-c/2019/ammks/0019',
    sectionHeader: 'Community Representations — Livelihood Impact Assessment',
    scanResolution: 'Scan Resolution: 600 DPI',
    zoom: 'Zoom 100%',
    ocrStreamMeta: 'ARCHIVAL OCR STREAM Joint Resolution Signatures',
    encoding: 'ENCODING: UTF-8 / RAW_FACSIMILE',
    preMatchText: 'Representatives of eight coastal fishing villages met in extraordinary council to review the loss of traditional artisanal shallow-water fish breeding grounds.',
    exactPassage: '“A unanimous resolution was passed calling on all coastal workers and civic youth alliances to mobilize in South Mumbai starting June 15 until formal judicial hearing is granted.”',
    relevance: '98.9% RELEVANCE',
    postMatchText: 'Copies of the resolution were served upon the Chief Minister’s Secretariat and the Mumbai Port Trust.',
    confidence: '98.9% (Civic Resolution Ground Truth)',
    justificationHtml: 'Supplies primary grounding for the escalation timetable and community mobilization trigger points in early/mid-June 2019.',
    tags: [
      { label: 'Temporal Alignment', value: 'Validated', icon: 'check' },
      { label: 'Geographic Scope', value: 'Worli & Cuffe Parade', icon: 'map' },
      { label: 'Attribution Class', value: 'Community Deposition', icon: 'building' }
    ],
    targetClaim: 'demonstrations had evolved into continuous civil assemblies [8]'
  }
};
